title: <p align="center"> Arkja Bajpai </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="/Arkja Bajpai SSE.docx">Resume</a> |
  <a href="https://www.linkedin.com/in/arkja-bajpai-397808a6/">LinkedIn</a> |
  <a href="https://github.com/Arkja1">GitHub</a>
  
  <br>   
    Will add details
  <br>



theme: jekyll-theme-minimal
